channels:
- conda-forge
dependencies:
  - nbsphinx
  - sphinx
  - myst-parser
  - numpy
  - ase =3.22.1
  - coverage
  - numpy =1.26.2
  - scipy =1.11.4
  - spglib =2.1.0
  - phonopy =2.20.0
  - structuretoolkit =0.0.11
  - seekpath =2.1.0
  - lammps =2023.08.02
  - pandas =2.1.3
  - pylammpsmpi =0.2.5
  - jinja2 =3.1.2