channels:
- conda-forge
dependencies:
- ase =3.22.1
- numpy =1.21.6
- scipy =1.11.1
- spglib =2.0.2
- phonopy =2.20.0
- structuretoolkit =0.0.10
- seekpath =1.9.0
- lammps =2022.06.23
- pandas =1.5.3
- pylammpsmpi =0.2.1
- jinja2 =2.11.3
- iprpy-data =2023.07.25