channels:
- conda-forge
dependencies:
- nbsphinx
- sphinx
- sphinx_rtd_theme
- myst-parser
- numpy
- ase =3.22.1
- coverage
- numpy =1.26.3
- scipy =1.13.1
- spglib =2.4.0
- phonopy =2.23.1
- structuretoolkit =0.0.23
- seekpath =2.1.0
- lammps =2023.11.21
- pandas =2.2.2
- pylammpsmpi =0.2.19
- jinja2 =3.1.4
- jupyter-book =1.0.0
