channels:
- conda-forge
dependencies:
- ase =3.22.1
- numpy =1.26.4
- scipy =1.13.0
- spglib =2.4.0
- phonopy =2.23.1
- structuretoolkit =0.0.22
- seekpath =2.1.0
- gpaw =24.1.0
- lammps =2024.02.07
- pandas =2.2.2
- pylammpsmpi =0.2.18
- jinja2 =3.1.3
