channels:
- conda-forge
dependencies:
- ase =3.23.0
- numpy =1.26.4
- scipy =1.13.1
- spglib =2.4.0
- phonopy =2.24.1
- structuretoolkit =0.0.24
- seekpath =2.1.0
- gpaw =24.6.0
- lammps =2024.02.07
- pandas =2.2.2
- pylammpsmpi =0.2.19
- jinja2 =3.1.4
- dynaphopy =1.17.15
- tqdm =4.66.4
