channels:
- conda-forge
dependencies:
- ase =3.22.1
- coverage
- numpy =1.26.4
- scipy =1.13.0
- spglib =2.3.1
- phonopy =2.22.1
- structuretoolkit =0.0.22
- seekpath =2.1.0
- gpaw =24.1.0
- lammps =2023.11.21
- pandas =2.2.1
- pylammpsmpi =0.2.15
- jinja2 =3.1.3
