name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup environment
      shell: bash -l {0}
      run: |
        cp .ci_support/environment.yml environment.yml
        tail --lines=+4 .ci_support/environment-lammps.yml >> environment.yml
        tail --lines=+4 .ci_support/environment-qe.yml >> environment.yml
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: '3.11'
        miniforge-variant: Mambaforge
        channels: conda-forge
        channel-priority: strict
        activate-environment: my-env
        environment-file: environment.yml
        use-mamba: true
    - name: Test
      shell: bash -l {0}
      timeout-minutes: 30
      run: |
        pip install versioneer[toml]==0.29
        pip install . --no-deps --no-build-isolation
        coverage run --omit="atomistics/_version.py,tests/*" -m unittest discover tests
        coverage xml
      env:
        ASE_ESPRESSO_COMMAND: "pw.x -in PREFIX.pwi > PREFIX.pwo"
        ESPRESSO_PSEUDO: tests/static/qe
        OMPI_MCA_plm: isolated
        OMPI_MCA_btl_vader_single_copy_mechanism: none
        OMPI_MCA_rmaps_base_oversubscribe: yes
    - name: Coveralls
      uses: coverallsapp/github-action@v2
