name: Unittest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        include:
        - operating-system: macos-latest
          python-version: '3.11'
          label: osx-64-py-3-11
          prefix: /Users/runner/miniconda3/envs/my-env

        - operating-system: ubuntu-latest
          python-version: '3.11'
          label: linux-64-py-3-11
          prefix: /usr/share/miniconda3/envs/my-env

        - operating-system: windows-latest
          python-version: '3.11'
          label: win-64-py-3-11
          prefix: /usr/share/miniconda3/envs/my-env

        - operating-system: ubuntu-latest
          python-version: '3.10'
          label: linux-64-py-3-10
          prefix: /usr/share/miniconda3/envs/my-env

        - operating-system: ubuntu-latest
          python-version: '3.9'
          label: linux-64-py-3-9
          prefix: /usr/share/miniconda3/envs/my-env
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        miniforge-variant: Mambaforge
        channels: conda-forge
        channel-priority: strict
        activate-environment: my-env
        use-mamba: true
    - name: Setup environment (windows)
      if: matrix.operating-system == 'windows-latest'
      run: cp .ci_support/environment.yml environment.yml
    - name: Setup environment (unix)
      if: matrix.operating-system != 'windows-latest'
      shell: bash -l {0}
      run: |
        mamba install -y pyyaml
        python .ci_support/condamerge.py --base .ci_support/environment.yml --add .ci_support/environment-lammps.yml > environment.yml
    - name: Update environment
      run: mamba env update -n my-env -f environment.yml
    - name: Setup
      shell: bash -l {0}
      run: |
        pip install --no-deps .
    - name: Test
      shell: bash -l {0}
      timeout-minutes: 30
      run: |
        coverage run --omit atomistics/_version.py -m unittest discover tests
        coverage combine
    - name: Coveralls
      if: matrix.label == 'linux-64-py-3-11'
      uses: coverallsapp/github-action@v2
