name: Quantum Espresso Unittest Linux 3.11

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Merge Notebook environment
      run: |
        cp .ci_support/environment.yml environment.yml
        tail --lines=+4 .ci_support/environment-abinit.yml >> environment.yml
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: '3.11'
        miniforge-variant: Mambaforge
        channels: conda-forge
        channel-priority: strict
        activate-environment: my-env
        environment-file: environment.yml
        use-mamba: true
    - name: Test
      shell: bash -l {0}
      timeout-minutes: 30
      run: |
        pip install --no-deps .
        python -m unittest tests/test_evcurve_qe.py
      env:
        ASE_ESPRESSO_COMMAND: "mpirun -np 1 pw.x -in PREFIX.pwi > PREFIX.pwo"
        ESPRESSO_PSEUDO: tests/static/qe
        OMPI_MCA_plm: isolated
        OMPI_MCA_btl_vader_single_copy_mechanism: none
        OMPI_MCA_rmaps_base_oversubscribe: yes
