name: Unittest

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        include:
        - operating-system: macos-latest
          python-version: '3.12'

        - operating-system: ubuntu-latest
          python-version: '3.12'

        - operating-system: windows-latest
          python-version: '3.12'

        - operating-system: ubuntu-latest
          python-version: '3.11'

        - operating-system: ubuntu-latest
          python-version: '3.10'
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup environment (windows)
      if: matrix.operating-system == 'windows-latest'
      shell: bash -l {0}
      run: |
        cp .ci_support/environment.yml environment.yml
        echo -e "channels:\n  - conda-forge\n" > .condarc
    - name: Setup environment (unix)
      if: matrix.operating-system != 'windows-latest'
      shell: bash -l {0}
      run: |
        cp .ci_support/environment.yml environment.yml
        tail --lines=+4 .ci_support/environment-lammps.yml >> environment.yml
        echo -e "channels:\n  - conda-forge\n" > .condarc
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        miniforge-version: latest
        condarc-file: .condarc
        environment-file: environment.yml
    - name: Test
      shell: bash -l {0}
      timeout-minutes: 30
      run: |
        pip install versioneer[toml]==0.29
        pip install . --no-deps --no-build-isolation
        python -m unittest discover tests
